on:
  push:
    branches:
      - gh-pages

jobs:
  jekyll_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source branch for building Pages
        uses: actions/checkout@v1
        with:
          ref: gh-pages
          fetch-depth: 10

      # Note the following may not be required in future versions of Jekyll Build Actions
      - name: Make build destination directory
        run: mkdir -vp ~/www/phec0fr9kuf.github.io

      - name: Jekyll Build
        uses: gha-utilities/jekyll-build@v0.0.1
        with:
          jekyll_github_token: ${{ secrets.JEKYLL_GITHUB_TOKEN }}
          source: ./
          destination: ~/www/phec0fr9kuf.github.io

      - name: Checkout branch for GitHub Pages
        uses: actions/checkout@v1
        with:
          ref: built-site
          fetch-depth: 1
          submodules: true

      - name: Copy built site files into Git branch
        run: cp -r ~/www/phec0fr9kuf.github.io ./

      - name: Add and Commit changes to built-site branch
        run: |
          git config --local user.email 'lamons.n@gmail.com'
          git config --local user.name 'GitHub Action'
          git add -A .
          git commit -m 'Updates compiled site files'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: built-site

      # - name: Initialize Pull Request
        # uses: gha-utilities/init-pull-request@v0.0.1
        # with:
          # pull_request_token: ${{ secrets.GITHUB_TOKEN }}
          # head: built-site
          # base: gh-pages
          # title: 'Updates site files from latest Actions build'
          # body: >
            # Perhaps a multi-line description
            # about latest features and such.
